# Configuración del pipeline en Azure DevOps para ejecutar pruebas por cada @pytest.mark
trigger:
  branches:
    include:
      - main  # Configura la rama que dispara el pipeline

variables:
  pythonVersion: '3.13'  # Define la versión de Python
  reportsHTMLPath: 'reports/html/report'
  reportsXMLPath: 'reports/xml/report'
  TEST_MARKS: 'blaze'  # Lista de marks

stages:
  - stage: BuildAndTest
    jobs:
      - job: InstallAndTest
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true

          - task: Cache@2
            inputs:
              key: 'pip | "$(Agent.OS)" | requirements.txt'
              restoreKeys: |
                pip | "$(Agent.OS)"
              path: $(Pipeline.Workspace)/.pip-cache
            displayName: 'Cache de dependencias de pip'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt --cache-dir $(Pipeline.Workspace)/.pip-cache
            displayName: 'Instala dependencias'
          
          # Ejecutar pruebas para cada marca definida en TEST_MARKS - ${{ each var in split(variables.TEST_MARKS, ', ') }}:
          - ${{ each mark in split(variables.TEST_MARKS, ' ') }}:
            - template: run-tests.yml
              parameters:
                mark: ${{ mark }}